/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AuditFitness.vista.auth;

import AuditFitness.vista.admin.AdminMenuView;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;

public class LoginAdminView extends javax.swing.JFrame {
    private String username;
    private String password;
    
    public LoginAdminView() {
        initComponents(); setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Round_JWC1 = new swing.Panel_Round_JWC();
        img_Autosize_JWC1 = new swing.Img_Autosize_JWC();
        LoginView = new swing.Panel_Round_JWC();
        BtnSalirRedondo = new swing.Btn_Round_JWC();
        jLabel1 = new javax.swing.JLabel();
        Usuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        Contrasenia = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        BtnIniciarSesion = new swing.Btn_Round_JWC();
        BtnAtras = new swing.Btn_Round_JWC();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_Round_JWC1.setBackground(new java.awt.Color(0, 0, 0));
        panel_Round_JWC1.setEsqInferiorDerecha(50);
        panel_Round_JWC1.setEsqInferiorIzquierda(50);
        panel_Round_JWC1.setEsqSuperiorDerecha(50);
        panel_Round_JWC1.setEsqSuperiorIzquierda(50);

        img_Autosize_JWC1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LOGO.png"))); // NOI18N

        LoginView.setBackground(new java.awt.Color(255, 255, 255));
        LoginView.setEsqInferiorDerecha(50);
        LoginView.setEsqSuperiorDerecha(50);
        LoginView.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnSalirRedondo.setBackground(new java.awt.Color(204, 102, 0));
        BtnSalirRedondo.setText("");
        BtnSalirRedondo.setArco_esquina(15);
        BtnSalirRedondo.setColor_H_text(new java.awt.Color(204, 102, 0));
        BtnSalirRedondo.setColor_Hover(new java.awt.Color(204, 102, 0));
        BtnSalirRedondo.setColor_Normal(new java.awt.Color(204, 102, 0));
        BtnSalirRedondo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirRedondoActionPerformed(evt);
            }
        });
        LoginView.add(BtnSalirRedondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 15, 15));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("LOGIN");
        LoginView.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        Usuario.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        Usuario.setForeground(new java.awt.Color(0, 0, 0));
        Usuario.setText("Usuario: ");
        LoginView.add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        txtUsuario.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuario.setToolTipText("");
        txtUsuario.setName("txtUsuario"); // NOI18N
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        LoginView.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 250, 30));
        txtUsuario.getAccessibleContext().setAccessibleName("Usuario");

        Contrasenia.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        Contrasenia.setForeground(new java.awt.Color(0, 0, 0));
        Contrasenia.setText("Contraseña:");
        LoginView.add(Contrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        txtPassword.setBackground(new java.awt.Color(255, 255, 255));
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        LoginView.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 250, 30));

        BtnIniciarSesion.setBackground(new java.awt.Color(204, 102, 0));
        BtnIniciarSesion.setText("Iniciar sesión");
        BtnIniciarSesion.setArco_esquina(20);
        BtnIniciarSesion.setColor_H_text(new java.awt.Color(204, 102, 0));
        BtnIniciarSesion.setColor_Normal(new java.awt.Color(204, 102, 0));
        BtnIniciarSesion.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        BtnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIniciarSesionActionPerformed(evt);
            }
        });
        LoginView.add(BtnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, 40));

        BtnAtras.setBackground(new java.awt.Color(204, 102, 0));
        BtnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/salida.png"))); // NOI18N
        BtnAtras.setText("");
        BtnAtras.setArco_esquina(20);
        BtnAtras.setColor_H_text(new java.awt.Color(204, 102, 0));
        BtnAtras.setColor_Hover(new java.awt.Color(255, 255, 255));
        BtnAtras.setColor_Normal(new java.awt.Color(204, 102, 0));
        BtnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtrasActionPerformed(evt);
            }
        });
        LoginView.add(BtnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, 50, 30));

        javax.swing.GroupLayout panel_Round_JWC1Layout = new javax.swing.GroupLayout(panel_Round_JWC1);
        panel_Round_JWC1.setLayout(panel_Round_JWC1Layout);
        panel_Round_JWC1Layout.setHorizontalGroup(
            panel_Round_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_Round_JWC1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(img_Autosize_JWC1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LoginView, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_Round_JWC1Layout.setVerticalGroup(
            panel_Round_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_Round_JWC1Layout.createSequentialGroup()
                .addContainerGap(145, Short.MAX_VALUE)
                .addComponent(img_Autosize_JWC1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
        );

        getContentPane().add(panel_Round_JWC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
      // Este método se puede usar para manejar el evento de presionar Enter en el campo de usuario
        txtPassword.requestFocus(); // Mover el foco al campo de contraseña
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void BtnSalirRedondoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirRedondoActionPerformed
        System.exit(0); // Cerrar la aplicación
    }//GEN-LAST:event_BtnSalirRedondoActionPerformed

    private void BtnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIniciarSesionActionPerformed
        String username = txtUsuario.getText().trim();
        String password = new String(txtPassword.getPassword()).trim();
        
        // Lógica para autenticar al administrador
        if (username.isEmpty() || password.isEmpty()) {
            mostrarMensaje("Por favor, complete todos los campos.");   
            return;
    }//GEN-LAST:event_BtnIniciarSesionActionPerformed

        // Validar credenciales desde el archivo CSV
        if (validarCredenciales(username, password)) {
            // Abrir el menú del administrador si las credenciales son correctas
            new AdminMenuView().setVisible(true);
            this.dispose(); // Cierra la vista de inicio de sesión
        } else {
            mostrarMensaje("Credenciales inválidas.");
        }
    }
        private boolean validarCredenciales(String username, String password) {
        String csvFile = "src/data/administradores.csv";
        String line;
        String[] credenciales;
        try (BufferedReader br = new BufferedReader(new FileReader(csvFile))) {
            while ((line = br.readLine()) != null) {
                credenciales = line.split(","); 
                if (credenciales[0].equals(username) && credenciales[1].equals(password)) {
                    return true; // Credenciales válidas
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        return false; // Credenciales no válidas
    }

    public void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {  
          BtnIniciarSesionActionPerformed(evt);
    }
    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }

    public String getUsername() {
        return username;
    }

    public String getPassword() {
        return password;
    }
    
    private void BtnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtrasActionPerformed
        RolView rol = new RolView();
        rol.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginAdminView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Btn_Round_JWC BtnAtras;
    public swing.Btn_Round_JWC BtnIniciarSesion;
    private swing.Btn_Round_JWC BtnSalirRedondo;
    private javax.swing.JLabel Contrasenia;
    private swing.Panel_Round_JWC LoginView;
    private javax.swing.JLabel Usuario;
    private swing.Img_Autosize_JWC img_Autosize_JWC1;
    private javax.swing.JLabel jLabel1;
    private swing.Panel_Round_JWC panel_Round_JWC1;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    
}


