/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AuditFitness;

import java.awt.Color;

/**
 *
 * @author deana
 */
public class ClienteMenuView extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public ClienteMenuView() {
        initComponents(); setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ClienteMenuView = new swing.Panel_Round_JWC();
        panel_Round_JWC2 = new swing.Panel_Round_JWC();
        BtnVerMiProgreso = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        BtnRegistrarAsistencia = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        BtnVerMisRutinas = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        jPanel1 = new javax.swing.JPanel();
        imagen_redondo_degradado_JWC1 = new img_redondo_degradado_jwc.imagen_redondo_degradado_JWC();
        jLabel1 = new javax.swing.JLabel();
        btn_Round_JWC1 = new swing.Btn_Round_JWC();
        btn_Round_JWC2 = new swing.Btn_Round_JWC();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ClienteMenuView");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ClienteMenuView.setBackground(new java.awt.Color(242, 240, 240));
        ClienteMenuView.setEsqInferiorDerecha(50);
        ClienteMenuView.setEsqInferiorIzquierda(50);
        ClienteMenuView.setEsqSuperiorDerecha(50);
        ClienteMenuView.setEsqSuperiorIzquierda(50);
        ClienteMenuView.setPreferredSize(new java.awt.Dimension(720, 620));

        panel_Round_JWC2.setBackground(new java.awt.Color(51, 51, 51));
        panel_Round_JWC2.setEsqInferiorIzquierda(50);
        panel_Round_JWC2.setEsqSuperiorIzquierda(50);
        panel_Round_JWC2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnVerMiProgreso.setForeground(new java.awt.Color(153, 153, 153));
        BtnVerMiProgreso.setText("Ver Mi Progreso");
        BtnVerMiProgreso.setBackground_Hover_1(new java.awt.Color(255, 102, 0));
        BtnVerMiProgreso.setBackground_Hover_2(new java.awt.Color(242, 240, 240));
        BtnVerMiProgreso.setBackground_No_Hover_1(new java.awt.Color(51, 51, 51));
        BtnVerMiProgreso.setBackground_No_Hover_2(new java.awt.Color(51, 51, 51));
        BtnVerMiProgreso.setBtn_abajo(BtnRegistrarAsistencia);
        BtnVerMiProgreso.setBtn_arriba(BtnVerMisRutinas);
        BtnVerMiProgreso.setBtn_arriba_abajo_esquina_ovalado(60);
        BtnVerMiProgreso.setColor_Hover_text(new java.awt.Color(0, 0, 0));
        BtnVerMiProgreso.setColor_NoHover_text(new java.awt.Color(153, 153, 153));
        BtnVerMiProgreso.setEsquina_inferior_izquierdo(40);
        BtnVerMiProgreso.setEsquina_superior_izquierdo(40);
        panel_Round_JWC2.add(BtnVerMiProgreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, 50));

        BtnRegistrarAsistencia.setForeground(new java.awt.Color(153, 153, 153));
        BtnRegistrarAsistencia.setText("Registrar Asistencia");
        BtnRegistrarAsistencia.setBackground_Hover_1(new java.awt.Color(255, 102, 0));
        BtnRegistrarAsistencia.setBackground_Hover_2(new java.awt.Color(242, 240, 240));
        BtnRegistrarAsistencia.setBackground_No_Hover_1(new java.awt.Color(51, 51, 51));
        BtnRegistrarAsistencia.setBackground_No_Hover_2(new java.awt.Color(51, 51, 51));
        BtnRegistrarAsistencia.setBtn_arriba(BtnVerMiProgreso);
        BtnRegistrarAsistencia.setBtn_arriba_abajo_esquina_ovalado(60);
        BtnRegistrarAsistencia.setColor_Hover_text(new java.awt.Color(0, 0, 0));
        BtnRegistrarAsistencia.setColor_NoHover_text(new java.awt.Color(153, 153, 153));
        BtnRegistrarAsistencia.setEsquina_inferior_izquierdo(40);
        BtnRegistrarAsistencia.setEsquina_superior_izquierdo(40);
        panel_Round_JWC2.add(BtnRegistrarAsistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, 50));

        BtnVerMisRutinas.setForeground(new java.awt.Color(153, 153, 153));
        BtnVerMisRutinas.setText("Ver Mis Rutinas");
        BtnVerMisRutinas.setBackground_Hover_1(new java.awt.Color(255, 102, 0));
        BtnVerMisRutinas.setBackground_Hover_2(new java.awt.Color(242, 240, 240));
        BtnVerMisRutinas.setBackground_No_Hover_1(new java.awt.Color(51, 51, 51));
        BtnVerMisRutinas.setBackground_No_Hover_2(new java.awt.Color(51, 51, 51));
        BtnVerMisRutinas.setBtn_abajo(BtnVerMiProgreso);
        BtnVerMisRutinas.setBtn_arriba_abajo_esquina_ovalado(60);
        BtnVerMisRutinas.setColor_Hover_text(new java.awt.Color(0, 0, 0));
        BtnVerMisRutinas.setColor_NoHover_text(new java.awt.Color(153, 153, 153));
        BtnVerMisRutinas.setEsquina_inferior_izquierdo(40);
        BtnVerMisRutinas.setEsquina_superior_izquierdo(40);
        BtnVerMisRutinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVerMisRutinasActionPerformed(evt);
            }
        });
        panel_Round_JWC2.add(BtnVerMisRutinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, 50));

        jPanel1.setBackground(new java.awt.Color(242, 240, 240));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panel_Round_JWC2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 50, 150));

        imagen_redondo_degradado_JWC1.setBorderSize(2);
        imagen_redondo_degradado_JWC1.setColo1(new java.awt.Color(255, 102, 0));
        imagen_redondo_degradado_JWC1.setColo2(new java.awt.Color(255, 204, 102));
        imagen_redondo_degradado_JWC1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images.png"))); // NOI18N
        panel_Round_JWC2.add(imagen_redondo_degradado_JWC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 110, 100));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username: Cliente");
        jLabel1.setToolTipText("");
        panel_Round_JWC2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 120, -1));

        btn_Round_JWC1.setBackground(new java.awt.Color(204, 102, 0));
        btn_Round_JWC1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/salida.png"))); // NOI18N
        btn_Round_JWC1.setText("");
        btn_Round_JWC1.setArco_esquina(20);
        btn_Round_JWC1.setColor_H_text(new java.awt.Color(204, 102, 0));
        btn_Round_JWC1.setColor_Hover(new java.awt.Color(255, 255, 255));
        btn_Round_JWC1.setColor_Normal(new java.awt.Color(204, 102, 0));
        btn_Round_JWC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Round_JWC1ActionPerformed(evt);
            }
        });
        panel_Round_JWC2.add(btn_Round_JWC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 190, 40));

        btn_Round_JWC2.setBackground(new java.awt.Color(204, 102, 0));
        btn_Round_JWC2.setText("");
        btn_Round_JWC2.setArco_esquina(15);
        btn_Round_JWC2.setColor_H_text(new java.awt.Color(204, 102, 0));
        btn_Round_JWC2.setColor_Hover(new java.awt.Color(204, 102, 0));
        btn_Round_JWC2.setColor_Normal(new java.awt.Color(204, 102, 0));
        btn_Round_JWC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Round_JWC2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ClienteMenuViewLayout = new javax.swing.GroupLayout(ClienteMenuView);
        ClienteMenuView.setLayout(ClienteMenuViewLayout);
        ClienteMenuViewLayout.setHorizontalGroup(
            ClienteMenuViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClienteMenuViewLayout.createSequentialGroup()
                .addComponent(panel_Round_JWC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 526, Short.MAX_VALUE)
                .addComponent(btn_Round_JWC2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        ClienteMenuViewLayout.setVerticalGroup(
            ClienteMenuViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Round_JWC2, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
            .addGroup(ClienteMenuViewLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btn_Round_JWC2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(ClienteMenuView, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 620));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Round_JWC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Round_JWC2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_Round_JWC2ActionPerformed

    private void btn_Round_JWC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Round_JWC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Round_JWC1ActionPerformed

    private void BtnVerMisRutinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVerMisRutinasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnVerMisRutinasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteMenuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private btn_efecto01_jwc.btn_efecto_V1_JWC BtnRegistrarAsistencia;
    private btn_efecto01_jwc.btn_efecto_V1_JWC BtnVerMiProgreso;
    private btn_efecto01_jwc.btn_efecto_V1_JWC BtnVerMisRutinas;
    private swing.Panel_Round_JWC ClienteMenuView;
    private swing.Btn_Round_JWC btn_Round_JWC1;
    private swing.Btn_Round_JWC btn_Round_JWC2;
    private img_redondo_degradado_jwc.imagen_redondo_degradado_JWC imagen_redondo_degradado_JWC1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private swing.Panel_Round_JWC panel_Round_JWC2;
    // End of variables declaration//GEN-END:variables
}
