/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AuditFitness.vista.cliente;

import AuditFitness.controlador.auth.SesionSingleton;
import AuditFitness.modelo.entidades.Asistencia;
import AuditFitness.modelo.repository.AsistenciaRepositoryImpl;
import AuditFitness.util.FechaHelper;
import AuditFitness.vista.auth.LoginClienteView;
import java.awt.Color;
import java.util.Calendar;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import javax.swing.JOptionPane;

/**
 *
 * @author deana
 */
public class RegistrarAsistenciaView extends javax.swing.JFrame {
    AsistenciaRepositoryImpl asistenciaRepositoryImpl = new AsistenciaRepositoryImpl();
    SesionSingleton sesionSingleton = SesionSingleton.getInstance();
    /**
     * Creates new form Inicio
     */
    public RegistrarAsistenciaView() {
        initComponents(); setBackground(new Color(0,0,0,0));
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ClienteMenuView = new swing.Panel_Round_JWC();
        panel_Round_JWC2 = new swing.Panel_Round_JWC();
        BtnVerMiProgreso = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        BtnRegistrarAsistencia = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        BtnVerMisRutinas = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        jPanel1 = new javax.swing.JPanel();
        imagen_redondo_degradado_JWC1 = new img_redondo_degradado_jwc.imagen_redondo_degradado_JWC();
        jLabel1 = new javax.swing.JLabel();
        BtnAtras = new swing.Btn_Round_JWC();
        BtnSalirRedondo = new swing.Btn_Round_JWC();
        jLabel2 = new javax.swing.JLabel();
        dateChooserAsistencia = new com.toedter.calendar.JDateChooser();
        BtnGuardarAsistencia = new swing.Btn_Round_JWC();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ClienteMenuView");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ClienteMenuView.setBackground(new java.awt.Color(242, 240, 240));
        ClienteMenuView.setEsqInferiorDerecha(50);
        ClienteMenuView.setEsqInferiorIzquierda(50);
        ClienteMenuView.setEsqSuperiorDerecha(50);
        ClienteMenuView.setEsqSuperiorIzquierda(50);
        ClienteMenuView.setPreferredSize(new java.awt.Dimension(720, 620));

        panel_Round_JWC2.setBackground(new java.awt.Color(51, 51, 51));
        panel_Round_JWC2.setEsqInferiorIzquierda(50);
        panel_Round_JWC2.setEsqSuperiorIzquierda(50);
        panel_Round_JWC2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnVerMiProgreso.setForeground(new java.awt.Color(153, 153, 153));
        BtnVerMiProgreso.setText("Ver Mi Progreso");
        BtnVerMiProgreso.setBackground_Hover_1(new java.awt.Color(255, 102, 0));
        BtnVerMiProgreso.setBackground_Hover_2(new java.awt.Color(242, 240, 240));
        BtnVerMiProgreso.setBackground_No_Hover_1(new java.awt.Color(51, 51, 51));
        BtnVerMiProgreso.setBackground_No_Hover_2(new java.awt.Color(51, 51, 51));
        BtnVerMiProgreso.setBtn_abajo(BtnRegistrarAsistencia);
        BtnVerMiProgreso.setBtn_arriba(BtnVerMisRutinas);
        BtnVerMiProgreso.setBtn_arriba_abajo_esquina_ovalado(60);
        BtnVerMiProgreso.setColor_Hover_text(new java.awt.Color(0, 0, 0));
        BtnVerMiProgreso.setColor_NoHover_text(new java.awt.Color(153, 153, 153));
        BtnVerMiProgreso.setEsquina_inferior_izquierdo(40);
        BtnVerMiProgreso.setEsquina_superior_izquierdo(40);
        BtnVerMiProgreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVerMiProgresoActionPerformed(evt);
            }
        });
        panel_Round_JWC2.add(BtnVerMiProgreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, 50));

        BtnRegistrarAsistencia.setForeground(new java.awt.Color(153, 153, 153));
        BtnRegistrarAsistencia.setText("Registrar Asistencia");
        BtnRegistrarAsistencia.setBackground_Hover_1(new java.awt.Color(255, 102, 0));
        BtnRegistrarAsistencia.setBackground_Hover_2(new java.awt.Color(242, 240, 240));
        BtnRegistrarAsistencia.setBackground_No_Hover_1(new java.awt.Color(51, 51, 51));
        BtnRegistrarAsistencia.setBackground_No_Hover_2(new java.awt.Color(51, 51, 51));
        BtnRegistrarAsistencia.setBtn_arriba(BtnVerMiProgreso);
        BtnRegistrarAsistencia.setBtn_arriba_abajo_esquina_ovalado(60);
        BtnRegistrarAsistencia.setColor_Hover_text(new java.awt.Color(0, 0, 0));
        BtnRegistrarAsistencia.setColor_NoHover_text(new java.awt.Color(153, 153, 153));
        BtnRegistrarAsistencia.setEsquina_inferior_izquierdo(40);
        BtnRegistrarAsistencia.setEsquina_superior_izquierdo(40);
        panel_Round_JWC2.add(BtnRegistrarAsistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, 50));

        BtnVerMisRutinas.setForeground(new java.awt.Color(153, 153, 153));
        BtnVerMisRutinas.setText("Ver Mis Rutinas");
        BtnVerMisRutinas.setBackground_Hover_1(new java.awt.Color(255, 102, 0));
        BtnVerMisRutinas.setBackground_Hover_2(new java.awt.Color(242, 240, 240));
        BtnVerMisRutinas.setBackground_No_Hover_1(new java.awt.Color(51, 51, 51));
        BtnVerMisRutinas.setBackground_No_Hover_2(new java.awt.Color(51, 51, 51));
        BtnVerMisRutinas.setBtn_abajo(BtnVerMiProgreso);
        BtnVerMisRutinas.setBtn_arriba_abajo_esquina_ovalado(60);
        BtnVerMisRutinas.setColor_Hover_text(new java.awt.Color(0, 0, 0));
        BtnVerMisRutinas.setColor_NoHover_text(new java.awt.Color(153, 153, 153));
        BtnVerMisRutinas.setEsquina_inferior_izquierdo(40);
        BtnVerMisRutinas.setEsquina_superior_izquierdo(40);
        BtnVerMisRutinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVerMisRutinasActionPerformed(evt);
            }
        });
        panel_Round_JWC2.add(BtnVerMisRutinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, 50));

        jPanel1.setBackground(new java.awt.Color(242, 240, 240));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panel_Round_JWC2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 50, 150));

        imagen_redondo_degradado_JWC1.setBorderSize(2);
        imagen_redondo_degradado_JWC1.setColo1(new java.awt.Color(255, 102, 0));
        imagen_redondo_degradado_JWC1.setColo2(new java.awt.Color(255, 204, 102));
        imagen_redondo_degradado_JWC1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images.png"))); // NOI18N
        panel_Round_JWC2.add(imagen_redondo_degradado_JWC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 110, 100));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username: Cliente");
        jLabel1.setToolTipText("");
        panel_Round_JWC2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 120, -1));

        BtnAtras.setBackground(new java.awt.Color(204, 102, 0));
        BtnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/salida.png"))); // NOI18N
        BtnAtras.setText("");
        BtnAtras.setArco_esquina(20);
        BtnAtras.setColor_H_text(new java.awt.Color(204, 102, 0));
        BtnAtras.setColor_Hover(new java.awt.Color(255, 255, 255));
        BtnAtras.setColor_Normal(new java.awt.Color(204, 102, 0));
        BtnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtrasActionPerformed(evt);
            }
        });
        panel_Round_JWC2.add(BtnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 190, 40));

        BtnSalirRedondo.setBackground(new java.awt.Color(204, 102, 0));
        BtnSalirRedondo.setText("");
        BtnSalirRedondo.setArco_esquina(15);
        BtnSalirRedondo.setColor_H_text(new java.awt.Color(204, 102, 0));
        BtnSalirRedondo.setColor_Hover(new java.awt.Color(204, 102, 0));
        BtnSalirRedondo.setColor_Normal(new java.awt.Color(204, 102, 0));
        BtnSalirRedondo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirRedondoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Registrar asistencia: ");

        dateChooserAsistencia.setBackground(new java.awt.Color(255, 102, 51));
        dateChooserAsistencia.setForeground(new java.awt.Color(242, 240, 240));
        dateChooserAsistencia.setAutoscrolls(true);
        dateChooserAsistencia.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        BtnGuardarAsistencia.setBackground(new java.awt.Color(204, 102, 0));
        BtnGuardarAsistencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/parte-superior-del-avion-de-papel.png"))); // NOI18N
        BtnGuardarAsistencia.setText("");
        BtnGuardarAsistencia.setArco_esquina(20);
        BtnGuardarAsistencia.setColor_H_text(new java.awt.Color(204, 102, 0));
        BtnGuardarAsistencia.setColor_Hover(new java.awt.Color(255, 153, 51));
        BtnGuardarAsistencia.setColor_Normal(new java.awt.Color(204, 102, 0));
        BtnGuardarAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarAsistenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ClienteMenuViewLayout = new javax.swing.GroupLayout(ClienteMenuView);
        ClienteMenuView.setLayout(ClienteMenuViewLayout);
        ClienteMenuViewLayout.setHorizontalGroup(
            ClienteMenuViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClienteMenuViewLayout.createSequentialGroup()
                .addComponent(panel_Round_JWC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(ClienteMenuViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClienteMenuViewLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnSalirRedondo, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(ClienteMenuViewLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(ClienteMenuViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClienteMenuViewLayout.createSequentialGroup()
                                .addComponent(dateChooserAsistencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnGuardarAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93))
                            .addGroup(ClienteMenuViewLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        ClienteMenuViewLayout.setVerticalGroup(
            ClienteMenuViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Round_JWC2, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
            .addGroup(ClienteMenuViewLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(ClienteMenuViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnGuardarAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ClienteMenuViewLayout.createSequentialGroup()
                        .addComponent(BtnSalirRedondo, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(dateChooserAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(ClienteMenuView, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 620));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSalirRedondoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirRedondoActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BtnSalirRedondoActionPerformed

    private void BtnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtrasActionPerformed
        LoginClienteView loginCliente = new LoginClienteView();
        loginCliente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnAtrasActionPerformed

    private void BtnVerMisRutinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVerMisRutinasActionPerformed
       abrirVerMisRutinasView();
    }//GEN-LAST:event_BtnVerMisRutinasActionPerformed

    private void abrirVerMisRutinasView() {
        VerMisRutinasView verMisRutinas  = new VerMisRutinasView();
        verMisRutinas.setVisible(true);
    }
    private Date getFechaRegistro(){
        Calendar selectedDate = dateChooserAsistencia.getCalendar();
        if(selectedDate!=null){
            return selectedDate.getTime();
        }
        
        return null;
    }
    private void BtnGuardarAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarAsistenciaActionPerformed
        // TODO add your handling code here:
        LocalDate fechaRegistro = getFechaRegistro().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        if(fechaRegistro!=null){            
            try {
                asistenciaRepositoryImpl.crear(new Asistencia(sesionSingleton.getIdenficacionSes(), fechaRegistro));
                JOptionPane.showMessageDialog(null, "Asistencia registrada con Exito!");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error al registrar asistencia", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            System.out.println("No ha seleccionado fecha");
        }
        
        /*String fech2="01-05-2025";
        Date fechaAlmacenada = FechaHelper.parsearFecha(fech2);
        dateChooserAsistencia.setDate(fechaAlmacenada);*/
        
    }//GEN-LAST:event_BtnGuardarAsistenciaActionPerformed

    private void BtnVerMiProgresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVerMiProgresoActionPerformed
        abrirVerMiProgresoView();
    }//GEN-LAST:event_BtnVerMiProgresoActionPerformed

    private void abrirVerMiProgresoView() {
        VerMiProgresoView verMiProgreso  = new VerMiProgresoView();
        verMiProgreso.setVisible(true);
        this.dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarAsistenciaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Btn_Round_JWC BtnAtras;
    private swing.Btn_Round_JWC BtnGuardarAsistencia;
    private btn_efecto01_jwc.btn_efecto_V1_JWC BtnRegistrarAsistencia;
    private swing.Btn_Round_JWC BtnSalirRedondo;
    private btn_efecto01_jwc.btn_efecto_V1_JWC BtnVerMiProgreso;
    private btn_efecto01_jwc.btn_efecto_V1_JWC BtnVerMisRutinas;
    private swing.Panel_Round_JWC ClienteMenuView;
    private com.toedter.calendar.JDateChooser dateChooserAsistencia;
    private img_redondo_degradado_jwc.imagen_redondo_degradado_JWC imagen_redondo_degradado_JWC1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private swing.Panel_Round_JWC panel_Round_JWC2;
    // End of variables declaration//GEN-END:variables
}
