/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AuditFitness;

import java.awt.Color;

/**
 *
 * @author deana
 */
public class AdminMenuView extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public AdminMenuView() {
        initComponents(); setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Round_JWC1 = new swing.Panel_Round_JWC();
        AdminMenuView = new swing.Panel_Round_JWC();
        BtnEliminarClientes = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        BtnAgregarEntrenador = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        BtnDesactEntrenador = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        BtnAgregarClientes = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        jPanel1 = new javax.swing.JPanel();
        imagen_redondo_degradado_JWC1 = new img_redondo_degradado_jwc.imagen_redondo_degradado_JWC();
        jLabel1 = new javax.swing.JLabel();
        BtnSalir = new swing.Btn_Round_JWC();
        btn_Round_JWC2 = new swing.Btn_Round_JWC();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_Round_JWC1.setBackground(new java.awt.Color(242, 240, 240));
        panel_Round_JWC1.setEsqInferiorDerecha(50);
        panel_Round_JWC1.setEsqInferiorIzquierda(50);
        panel_Round_JWC1.setEsqSuperiorDerecha(50);
        panel_Round_JWC1.setEsqSuperiorIzquierda(50);

        AdminMenuView.setBackground(new java.awt.Color(51, 51, 51));
        AdminMenuView.setEsqInferiorIzquierda(50);
        AdminMenuView.setEsqSuperiorIzquierda(50);
        AdminMenuView.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnEliminarClientes.setForeground(new java.awt.Color(153, 153, 153));
        BtnEliminarClientes.setText("Eliminar Clientes");
        BtnEliminarClientes.setBackground_Hover_1(new java.awt.Color(255, 102, 0));
        BtnEliminarClientes.setBackground_Hover_2(new java.awt.Color(242, 240, 240));
        BtnEliminarClientes.setBackground_No_Hover_1(new java.awt.Color(51, 51, 51));
        BtnEliminarClientes.setBackground_No_Hover_2(new java.awt.Color(51, 51, 51));
        BtnEliminarClientes.setBtn_abajo(BtnAgregarEntrenador);
        BtnEliminarClientes.setBtn_arriba(BtnAgregarClientes);
        BtnEliminarClientes.setBtn_arriba_abajo_esquina_ovalado(60);
        BtnEliminarClientes.setColor_Hover_text(new java.awt.Color(0, 0, 0));
        BtnEliminarClientes.setColor_NoHover_text(new java.awt.Color(153, 153, 153));
        BtnEliminarClientes.setEsquina_inferior_izquierdo(40);
        BtnEliminarClientes.setEsquina_superior_izquierdo(40);
        AdminMenuView.add(BtnEliminarClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, 50));

        BtnAgregarEntrenador.setForeground(new java.awt.Color(153, 153, 153));
        BtnAgregarEntrenador.setText("Agregar Entrenador");
        BtnAgregarEntrenador.setBackground_Hover_1(new java.awt.Color(255, 102, 0));
        BtnAgregarEntrenador.setBackground_Hover_2(new java.awt.Color(242, 240, 240));
        BtnAgregarEntrenador.setBackground_No_Hover_1(new java.awt.Color(51, 51, 51));
        BtnAgregarEntrenador.setBackground_No_Hover_2(new java.awt.Color(51, 51, 51));
        BtnAgregarEntrenador.setBtn_abajo(BtnDesactEntrenador);
        BtnAgregarEntrenador.setBtn_arriba(BtnEliminarClientes);
        BtnAgregarEntrenador.setBtn_arriba_abajo_esquina_ovalado(60);
        BtnAgregarEntrenador.setColor_Hover_text(new java.awt.Color(0, 0, 0));
        BtnAgregarEntrenador.setColor_NoHover_text(new java.awt.Color(153, 153, 153));
        BtnAgregarEntrenador.setEsquina_inferior_izquierdo(40);
        BtnAgregarEntrenador.setEsquina_superior_izquierdo(40);
        AdminMenuView.add(BtnAgregarEntrenador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, 50));

        BtnDesactEntrenador.setForeground(new java.awt.Color(153, 153, 153));
        BtnDesactEntrenador.setText("Desactivar Entrenador");
        BtnDesactEntrenador.setBackground_Hover_1(new java.awt.Color(255, 102, 0));
        BtnDesactEntrenador.setBackground_Hover_2(new java.awt.Color(242, 240, 240));
        BtnDesactEntrenador.setBackground_No_Hover_1(new java.awt.Color(51, 51, 51));
        BtnDesactEntrenador.setBackground_No_Hover_2(new java.awt.Color(51, 51, 51));
        BtnDesactEntrenador.setBtn_arriba(BtnAgregarEntrenador);
        BtnDesactEntrenador.setBtn_arriba_abajo_esquina_ovalado(60);
        BtnDesactEntrenador.setColor_Hover_text(new java.awt.Color(0, 0, 0));
        BtnDesactEntrenador.setColor_NoHover_text(new java.awt.Color(153, 153, 153));
        BtnDesactEntrenador.setEsquina_inferior_izquierdo(40);
        BtnDesactEntrenador.setEsquina_superior_izquierdo(40);
        AdminMenuView.add(BtnDesactEntrenador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, 50));

        BtnAgregarClientes.setForeground(new java.awt.Color(153, 153, 153));
        BtnAgregarClientes.setText("Agregar Clientes");
        BtnAgregarClientes.setBackground_Hover_1(new java.awt.Color(255, 102, 0));
        BtnAgregarClientes.setBackground_Hover_2(new java.awt.Color(242, 240, 240));
        BtnAgregarClientes.setBackground_No_Hover_1(new java.awt.Color(51, 51, 51));
        BtnAgregarClientes.setBackground_No_Hover_2(new java.awt.Color(51, 51, 51));
        BtnAgregarClientes.setBtn_abajo(BtnEliminarClientes);
        BtnAgregarClientes.setBtn_arriba_abajo_esquina_ovalado(60);
        BtnAgregarClientes.setColor_Hover_text(new java.awt.Color(0, 0, 0));
        BtnAgregarClientes.setColor_NoHover_text(new java.awt.Color(153, 153, 153));
        BtnAgregarClientes.setEsquina_inferior_izquierdo(40);
        BtnAgregarClientes.setEsquina_superior_izquierdo(40);
        BtnAgregarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarClientesActionPerformed(evt);
            }
        });
        AdminMenuView.add(BtnAgregarClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, 50));

        jPanel1.setBackground(new java.awt.Color(242, 240, 240));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        AdminMenuView.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 50, 200));

        imagen_redondo_degradado_JWC1.setBorderSize(2);
        imagen_redondo_degradado_JWC1.setColo1(new java.awt.Color(255, 102, 0));
        imagen_redondo_degradado_JWC1.setColo2(new java.awt.Color(255, 204, 102));
        imagen_redondo_degradado_JWC1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images.png"))); // NOI18N
        AdminMenuView.add(imagen_redondo_degradado_JWC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 110, 100));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username: Admin");
        jLabel1.setToolTipText("");
        AdminMenuView.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 110, -1));

        BtnSalir.setBackground(new java.awt.Color(204, 102, 0));
        BtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/salida.png"))); // NOI18N
        BtnSalir.setText("");
        BtnSalir.setToolTipText("");
        BtnSalir.setArco_esquina(20);
        BtnSalir.setColor_H_text(new java.awt.Color(204, 102, 0));
        BtnSalir.setColor_Hover(new java.awt.Color(255, 255, 255));
        BtnSalir.setColor_Normal(new java.awt.Color(204, 102, 0));
        AdminMenuView.add(BtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 190, 40));

        btn_Round_JWC2.setBackground(new java.awt.Color(204, 102, 0));
        btn_Round_JWC2.setText("");
        btn_Round_JWC2.setArco_esquina(15);
        btn_Round_JWC2.setColor_H_text(new java.awt.Color(204, 102, 0));
        btn_Round_JWC2.setColor_Hover(new java.awt.Color(204, 102, 0));
        btn_Round_JWC2.setColor_Normal(new java.awt.Color(204, 102, 0));
        btn_Round_JWC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Round_JWC2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_Round_JWC1Layout = new javax.swing.GroupLayout(panel_Round_JWC1);
        panel_Round_JWC1.setLayout(panel_Round_JWC1Layout);
        panel_Round_JWC1Layout.setHorizontalGroup(
            panel_Round_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Round_JWC1Layout.createSequentialGroup()
                .addComponent(AdminMenuView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 719, Short.MAX_VALUE)
                .addComponent(btn_Round_JWC2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        panel_Round_JWC1Layout.setVerticalGroup(
            panel_Round_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminMenuView, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
            .addGroup(panel_Round_JWC1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btn_Round_JWC2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panel_Round_JWC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 620));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAgregarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAgregarClientesActionPerformed

    private void btn_Round_JWC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Round_JWC2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_Round_JWC2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMenuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Panel_Round_JWC AdminMenuView;
    private btn_efecto01_jwc.btn_efecto_V1_JWC BtnAgregarClientes;
    private btn_efecto01_jwc.btn_efecto_V1_JWC BtnAgregarEntrenador;
    private btn_efecto01_jwc.btn_efecto_V1_JWC BtnDesactEntrenador;
    private btn_efecto01_jwc.btn_efecto_V1_JWC BtnEliminarClientes;
    private swing.Btn_Round_JWC BtnSalir;
    private swing.Btn_Round_JWC btn_Round_JWC2;
    private img_redondo_degradado_jwc.imagen_redondo_degradado_JWC imagen_redondo_degradado_JWC1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private swing.Panel_Round_JWC panel_Round_JWC1;
    // End of variables declaration//GEN-END:variables
}
