/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AuditFitness.vista.admin;

import AuditFitness.modelo.entidades.Cliente;
import AuditFitness.vista.auth.LoginAdminView;
import java.awt.Color;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author deana
 */
public class AgregarClientesView extends javax.swing.JFrame {
    /**
     * Creates new form Inicio
     */
    public AgregarClientesView() {
        initComponents(); setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Round_JWC1 = new swing.Panel_Round_JWC();
        AdminMenuView = new swing.Panel_Round_JWC();
        BtnEliminarClientes = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        BtnAgregarEntrenador = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        BtnDesactEntrenador = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        BtnAgregarClientes = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        jPanel1 = new javax.swing.JPanel();
        imagen_redondo_degradado_JWC1 = new img_redondo_degradado_jwc.imagen_redondo_degradado_JWC();
        jLabel1 = new javax.swing.JLabel();
        BtnSalir = new swing.Btn_Round_JWC();
        BtnSalirRedondo = new swing.Btn_Round_JWC();
        jLabel2 = new javax.swing.JLabel();
        txtIdentificacion = new javax.swing.JFormattedTextField();
        BtnEnviar = new swing.Btn_Round_JWC();
        jLabel3 = new javax.swing.JLabel();
        TablaClientesAgg = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BtnFormularioClientes = new swing.Btn_Round_JWC();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_Round_JWC1.setBackground(new java.awt.Color(242, 240, 240));
        panel_Round_JWC1.setEsqInferiorDerecha(50);
        panel_Round_JWC1.setEsqInferiorIzquierda(50);
        panel_Round_JWC1.setEsqSuperiorDerecha(50);
        panel_Round_JWC1.setEsqSuperiorIzquierda(50);

        AdminMenuView.setBackground(new java.awt.Color(51, 51, 51));
        AdminMenuView.setEsqInferiorIzquierda(50);
        AdminMenuView.setEsqSuperiorIzquierda(50);
        AdminMenuView.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnEliminarClientes.setForeground(new java.awt.Color(153, 153, 153));
        BtnEliminarClientes.setText("Eliminar Clientes");
        BtnEliminarClientes.setBackground_Hover_1(new java.awt.Color(255, 102, 0));
        BtnEliminarClientes.setBackground_Hover_2(new java.awt.Color(242, 240, 240));
        BtnEliminarClientes.setBackground_No_Hover_1(new java.awt.Color(51, 51, 51));
        BtnEliminarClientes.setBackground_No_Hover_2(new java.awt.Color(51, 51, 51));
        BtnEliminarClientes.setBtn_abajo(BtnAgregarEntrenador);
        BtnEliminarClientes.setBtn_arriba(BtnAgregarClientes);
        BtnEliminarClientes.setBtn_arriba_abajo_esquina_ovalado(60);
        BtnEliminarClientes.setColor_Hover_text(new java.awt.Color(0, 0, 0));
        BtnEliminarClientes.setColor_NoHover_text(new java.awt.Color(153, 153, 153));
        BtnEliminarClientes.setEsquina_inferior_izquierdo(40);
        BtnEliminarClientes.setEsquina_superior_izquierdo(40);
        BtnEliminarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarClientesActionPerformed(evt);
            }
        });
        AdminMenuView.add(BtnEliminarClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, 50));

        BtnAgregarEntrenador.setForeground(new java.awt.Color(153, 153, 153));
        BtnAgregarEntrenador.setText("Agregar Entrenador");
        BtnAgregarEntrenador.setBackground_Hover_1(new java.awt.Color(255, 102, 0));
        BtnAgregarEntrenador.setBackground_Hover_2(new java.awt.Color(242, 240, 240));
        BtnAgregarEntrenador.setBackground_No_Hover_1(new java.awt.Color(51, 51, 51));
        BtnAgregarEntrenador.setBackground_No_Hover_2(new java.awt.Color(51, 51, 51));
        BtnAgregarEntrenador.setBtn_abajo(BtnDesactEntrenador);
        BtnAgregarEntrenador.setBtn_arriba(BtnEliminarClientes);
        BtnAgregarEntrenador.setBtn_arriba_abajo_esquina_ovalado(60);
        BtnAgregarEntrenador.setColor_Hover_text(new java.awt.Color(0, 0, 0));
        BtnAgregarEntrenador.setColor_NoHover_text(new java.awt.Color(153, 153, 153));
        BtnAgregarEntrenador.setEsquina_inferior_izquierdo(40);
        BtnAgregarEntrenador.setEsquina_superior_izquierdo(40);
        BtnAgregarEntrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarEntrenadorActionPerformed(evt);
            }
        });
        AdminMenuView.add(BtnAgregarEntrenador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, 50));

        BtnDesactEntrenador.setForeground(new java.awt.Color(153, 153, 153));
        BtnDesactEntrenador.setText("Desactivar Entrenador");
        BtnDesactEntrenador.setBackground_Hover_1(new java.awt.Color(255, 102, 0));
        BtnDesactEntrenador.setBackground_Hover_2(new java.awt.Color(242, 240, 240));
        BtnDesactEntrenador.setBackground_No_Hover_1(new java.awt.Color(51, 51, 51));
        BtnDesactEntrenador.setBackground_No_Hover_2(new java.awt.Color(51, 51, 51));
        BtnDesactEntrenador.setBtn_arriba(BtnAgregarEntrenador);
        BtnDesactEntrenador.setBtn_arriba_abajo_esquina_ovalado(60);
        BtnDesactEntrenador.setColor_Hover_text(new java.awt.Color(0, 0, 0));
        BtnDesactEntrenador.setColor_NoHover_text(new java.awt.Color(153, 153, 153));
        BtnDesactEntrenador.setEsquina_inferior_izquierdo(40);
        BtnDesactEntrenador.setEsquina_superior_izquierdo(40);
        BtnDesactEntrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDesactEntrenadorActionPerformed(evt);
            }
        });
        AdminMenuView.add(BtnDesactEntrenador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, 50));

        BtnAgregarClientes.setForeground(new java.awt.Color(153, 153, 153));
        BtnAgregarClientes.setText("Agregar Clientes");
        BtnAgregarClientes.setBackground_Hover_1(new java.awt.Color(255, 102, 0));
        BtnAgregarClientes.setBackground_Hover_2(new java.awt.Color(242, 240, 240));
        BtnAgregarClientes.setBackground_No_Hover_1(new java.awt.Color(51, 51, 51));
        BtnAgregarClientes.setBackground_No_Hover_2(new java.awt.Color(51, 51, 51));
        BtnAgregarClientes.setBtn_abajo(BtnEliminarClientes);
        BtnAgregarClientes.setBtn_arriba_abajo_esquina_ovalado(60);
        BtnAgregarClientes.setColor_Hover_text(new java.awt.Color(0, 0, 0));
        BtnAgregarClientes.setColor_NoHover_text(new java.awt.Color(153, 153, 153));
        BtnAgregarClientes.setEsquina_inferior_izquierdo(40);
        BtnAgregarClientes.setEsquina_superior_izquierdo(40);
        BtnAgregarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarClientesActionPerformed(evt);
            }
        });
        AdminMenuView.add(BtnAgregarClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, 50));

        jPanel1.setBackground(new java.awt.Color(242, 240, 240));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        AdminMenuView.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 50, 200));

        imagen_redondo_degradado_JWC1.setBorderSize(2);
        imagen_redondo_degradado_JWC1.setColo1(new java.awt.Color(255, 102, 0));
        imagen_redondo_degradado_JWC1.setColo2(new java.awt.Color(255, 204, 102));
        imagen_redondo_degradado_JWC1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images.png"))); // NOI18N
        AdminMenuView.add(imagen_redondo_degradado_JWC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 110, 100));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username: Admin");
        jLabel1.setToolTipText("");
        AdminMenuView.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 110, -1));

        BtnSalir.setBackground(new java.awt.Color(204, 102, 0));
        BtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/salida.png"))); // NOI18N
        BtnSalir.setText("");
        BtnSalir.setToolTipText("");
        BtnSalir.setArco_esquina(20);
        BtnSalir.setColor_H_text(new java.awt.Color(204, 102, 0));
        BtnSalir.setColor_Hover(new java.awt.Color(255, 255, 255));
        BtnSalir.setColor_Normal(new java.awt.Color(204, 102, 0));
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });
        AdminMenuView.add(BtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 190, 40));

        BtnSalirRedondo.setBackground(new java.awt.Color(204, 102, 0));
        BtnSalirRedondo.setText("");
        BtnSalirRedondo.setArco_esquina(15);
        BtnSalirRedondo.setColor_H_text(new java.awt.Color(204, 102, 0));
        BtnSalirRedondo.setColor_Hover(new java.awt.Color(204, 102, 0));
        BtnSalirRedondo.setColor_Normal(new java.awt.Color(204, 102, 0));
        BtnSalirRedondo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirRedondoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Agregar Cliente:");

        txtIdentificacion.setBackground(new java.awt.Color(255, 255, 255));
        txtIdentificacion.setForeground(new java.awt.Color(0, 0, 0));
        txtIdentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdentificacionActionPerformed(evt);
            }
        });

        BtnEnviar.setBackground(new java.awt.Color(204, 102, 0));
        BtnEnviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/parte-superior-del-avion-de-papel.png"))); // NOI18N
        BtnEnviar.setText("");
        BtnEnviar.setArco_esquina(20);
        BtnEnviar.setColor_H_text(new java.awt.Color(204, 102, 0));
        BtnEnviar.setColor_Hover(new java.awt.Color(255, 153, 51));
        BtnEnviar.setColor_Normal(new java.awt.Color(204, 102, 0));
        BtnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEnviarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Ingrese la identificación del cliente: ");

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 102, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Identificación", "Nombre", "Usuario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        jTable1.setGridColor(new java.awt.Color(255, 102, 0));
        jTable1.setRowHeight(25);
        TablaClientesAgg.setViewportView(jTable1);

        BtnFormularioClientes.setBackground(new java.awt.Color(204, 102, 0));
        BtnFormularioClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/agregar (1).png"))); // NOI18N
        BtnFormularioClientes.setText("");
        BtnFormularioClientes.setArco_esquina(20);
        BtnFormularioClientes.setColor_H_text(new java.awt.Color(204, 102, 0));
        BtnFormularioClientes.setColor_Hover(new java.awt.Color(255, 153, 51));
        BtnFormularioClientes.setColor_Normal(new java.awt.Color(204, 102, 0));
        BtnFormularioClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFormularioClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_Round_JWC1Layout = new javax.swing.GroupLayout(panel_Round_JWC1);
        panel_Round_JWC1.setLayout(panel_Round_JWC1Layout);
        panel_Round_JWC1Layout.setHorizontalGroup(
            panel_Round_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Round_JWC1Layout.createSequentialGroup()
                .addComponent(AdminMenuView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panel_Round_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_Round_JWC1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnSalirRedondo, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(panel_Round_JWC1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(panel_Round_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addGroup(panel_Round_JWC1Layout.createSequentialGroup()
                                .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnFormularioClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TablaClientesAgg, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(72, Short.MAX_VALUE))))
        );
        panel_Round_JWC1Layout.setVerticalGroup(
            panel_Round_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminMenuView, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
            .addGroup(panel_Round_JWC1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(BtnSalirRedondo, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_Round_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnFormularioClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(TablaClientesAgg, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panel_Round_JWC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 620));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAgregarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarClientesActionPerformed
        abrirAgregarClientesView();
    }//GEN-LAST:event_BtnAgregarClientesActionPerformed

    private void BtnSalirRedondoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirRedondoActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BtnSalirRedondoActionPerformed

    private void txtIdentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdentificacionActionPerformed
        BtnEnviarActionPerformed(evt);
    }//GEN-LAST:event_txtIdentificacionActionPerformed

    private void BtnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEnviarActionPerformed
    String identificacion = txtIdentificacion.getText().trim(); // Obtener la identificación ingresada
    // Validar que la identificación no esté vacía
    if (identificacion.isEmpty()) {
        mostrarMensaje("Por favor, ingresa una identificación válida.");
        return; 
    }     
    // Validar identificación desde el archivo CSV
    Cliente cliente = cargarClientePorIdentificacion(identificacion);
    if (cliente != null) {
        // Si el cliente existe, mostrarlo en la tabla
        mostrarClienteEnTabla(cliente);
    } else {
        mostrarMensaje("Usuario no encontrado.");
    }
    }//GEN-LAST:event_BtnEnviarActionPerformed
    
    private void BtnEliminarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarClientesActionPerformed
       abrirEliminarClientesView();
    }//GEN-LAST:event_BtnEliminarClientesActionPerformed

    private void BtnAgregarEntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarEntrenadorActionPerformed
        abrirAgregarEntrenadorView();
    }//GEN-LAST:event_BtnAgregarEntrenadorActionPerformed

    private void BtnDesactEntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDesactEntrenadorActionPerformed
        abrirDesactivarEntrenadorView();
    }//GEN-LAST:event_BtnDesactEntrenadorActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
       LoginAdminView loginAdmin = new LoginAdminView();
       loginAdmin.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void BtnFormularioClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFormularioClientesActionPerformed
        // Crear y mostrar la vista del formulario de cliente
        FormularioClientesView formularioClientesView = new FormularioClientesView(this, true);
        formularioClientesView.setVisible(true);
    }//GEN-LAST:event_BtnFormularioClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarClientesView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Panel_Round_JWC AdminMenuView;
    private btn_efecto01_jwc.btn_efecto_V1_JWC BtnAgregarClientes;
    private btn_efecto01_jwc.btn_efecto_V1_JWC BtnAgregarEntrenador;
    private btn_efecto01_jwc.btn_efecto_V1_JWC BtnDesactEntrenador;
    private btn_efecto01_jwc.btn_efecto_V1_JWC BtnEliminarClientes;
    private swing.Btn_Round_JWC BtnEnviar;
    private swing.Btn_Round_JWC BtnFormularioClientes;
    private swing.Btn_Round_JWC BtnSalir;
    private swing.Btn_Round_JWC BtnSalirRedondo;
    private javax.swing.JScrollPane TablaClientesAgg;
    private img_redondo_degradado_jwc.imagen_redondo_degradado_JWC imagen_redondo_degradado_JWC1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable jTable1;
    private swing.Panel_Round_JWC panel_Round_JWC1;
    private javax.swing.JFormattedTextField txtIdentificacion;
    // End of variables declaration//GEN-END:variables

    private void abrirEliminarClientesView() {
        EliminarClientesView eliminarClientes = new EliminarClientesView ();
        eliminarClientes.setVisible(true);
        this.dispose();
    }

    private void abrirAgregarEntrenadorView() {
        AgregarEntrenadorView agregarEntrenador = new AgregarEntrenadorView ();
        agregarEntrenador.setVisible(true);
        this.dispose();
    }

    private void abrirDesactivarEntrenadorView() {
        DesactivarEntrenadorView desactivarEntrenador = new DesactivarEntrenadorView();
        desactivarEntrenador.setVisible(true);
        this.dispose();
    }

    private void abrirAgregarClientesView() {
        AgregarClientesView agregarClientes = new AgregarClientesView ();
        agregarClientes.setVisible(true);
        this.dispose();
    }

    public String getIdentificacion() {
        return null;
    }

    public void mostrarClientes(Object[][] data, String[] columnNames) {
        
    }

    public void abrirFormularioClientesView(Frame vista) {
    FormularioClientesView formularioClientesView = new FormularioClientesView(vista, true);
    formularioClientesView.setVisible(true);
    formularioClientesView.agregarListenerRegistrar(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            // Obtener los datos del formulario
            String nombre = formularioClientesView.getNombre();
            String identificacion = formularioClientesView.getIdentificacion();
            String contraseña = formularioClientesView.getContraseña();
            String confirmarContraseña = formularioClientesView.getConfirmarContraseña();

            // Si el registro es exitoso:
            formularioClientesView.mostrarMensaje("Cliente registrado exitosamente.");
            formularioClientesView.limpiarCampos(); // Limpiar campos después de registrar
        }
    });
    }
    
    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    private Cliente cargarClientePorIdentificacion(String identificacion) {
    String csvFile = "src/data/clientes.csv";
    String line;
    String[] datosCliente;
    try (BufferedReader br = new BufferedReader(new FileReader(csvFile))) {
        while ((line = br.readLine()) != null) {
            datosCliente = line.split(","); 
            if (datosCliente[3].equals(identificacion)) { // Suponiendo que la identificación está en la posición 3
                String username = datosCliente[0];
                String password = datosCliente[1];
                String nombre = datosCliente[2];
                return new Cliente(username, password, nombre, identificacion); // Retornar el cliente encontrado
            }
        }
    } catch (IOException e) {
        e.printStackTrace();
    }
    return null; // Retornar null si no se encuentra el cliente
}
    private void mostrarClienteEnTabla(Cliente cliente) {
    // Crear un modelo de datos para la tabla
    String[] columnNames = {"Username", "Nombre", "Identificación"};
    Object[][] data = {
        {cliente.getUsername(), cliente.getNombre(), cliente.getIdentificacion()}
    };
    // Crear un modelo de tabla y asignarlo al JTable
    DefaultTableModel model = new DefaultTableModel(data, columnNames);
    jTable1.setModel(model); // Asignar el modelo al JTable
}

    public void agregarListenerFormularioClientes(ActionListener actionListener) {
        
    }

    public void abrirFormularioClientesView() {
        
    }
    
}

