/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AuditFitness.vista.admin;

import AuditFitness.modelo.repository.EntrenadorRepositoryImpl;
import AuditFitness.vista.auth.LoginAdminView;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author deana
 */
public class DesactivarEntrenadorView extends javax.swing.JFrame {
    
    private EntrenadorRepositoryImpl entrenadorRepository = new EntrenadorRepositoryImpl();
    /**
     * Creates new form Inicio
     */
    public DesactivarEntrenadorView() {
        initComponents(); setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Round_JWC1 = new swing.Panel_Round_JWC();
        AdminMenuView = new swing.Panel_Round_JWC();
        BtnEliminarClientes = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        BtnAgregarEntrenador = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        BtnDesactEntrenador = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        BtnAgregarClientes = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        jPanel1 = new javax.swing.JPanel();
        imagen_redondo_degradado_JWC1 = new img_redondo_degradado_jwc.imagen_redondo_degradado_JWC();
        jLabel1 = new javax.swing.JLabel();
        BtnSalir = new swing.Btn_Round_JWC();
        BtnSalirRedondo = new swing.Btn_Round_JWC();
        jLabel2 = new javax.swing.JLabel();
        Identificacion = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        BtnEliminar = new swing.Btn_Round_JWC();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_Round_JWC1.setBackground(new java.awt.Color(242, 240, 240));
        panel_Round_JWC1.setEsqInferiorDerecha(50);
        panel_Round_JWC1.setEsqInferiorIzquierda(50);
        panel_Round_JWC1.setEsqSuperiorDerecha(50);
        panel_Round_JWC1.setEsqSuperiorIzquierda(50);

        AdminMenuView.setBackground(new java.awt.Color(51, 51, 51));
        AdminMenuView.setEsqInferiorIzquierda(50);
        AdminMenuView.setEsqSuperiorIzquierda(50);
        AdminMenuView.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnEliminarClientes.setForeground(new java.awt.Color(153, 153, 153));
        BtnEliminarClientes.setText("Eliminar Clientes");
        BtnEliminarClientes.setBackground_Hover_1(new java.awt.Color(255, 102, 0));
        BtnEliminarClientes.setBackground_Hover_2(new java.awt.Color(242, 240, 240));
        BtnEliminarClientes.setBackground_No_Hover_1(new java.awt.Color(51, 51, 51));
        BtnEliminarClientes.setBackground_No_Hover_2(new java.awt.Color(51, 51, 51));
        BtnEliminarClientes.setBtn_abajo(BtnAgregarEntrenador);
        BtnEliminarClientes.setBtn_arriba(BtnAgregarClientes);
        BtnEliminarClientes.setBtn_arriba_abajo_esquina_ovalado(60);
        BtnEliminarClientes.setColor_Hover_text(new java.awt.Color(0, 0, 0));
        BtnEliminarClientes.setColor_NoHover_text(new java.awt.Color(153, 153, 153));
        BtnEliminarClientes.setEsquina_inferior_izquierdo(40);
        BtnEliminarClientes.setEsquina_superior_izquierdo(40);
        BtnEliminarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarClientesActionPerformed(evt);
            }
        });
        AdminMenuView.add(BtnEliminarClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, 50));

        BtnAgregarEntrenador.setForeground(new java.awt.Color(153, 153, 153));
        BtnAgregarEntrenador.setText("Agregar Entrenador");
        BtnAgregarEntrenador.setBackground_Hover_1(new java.awt.Color(255, 102, 0));
        BtnAgregarEntrenador.setBackground_Hover_2(new java.awt.Color(242, 240, 240));
        BtnAgregarEntrenador.setBackground_No_Hover_1(new java.awt.Color(51, 51, 51));
        BtnAgregarEntrenador.setBackground_No_Hover_2(new java.awt.Color(51, 51, 51));
        BtnAgregarEntrenador.setBtn_abajo(BtnDesactEntrenador);
        BtnAgregarEntrenador.setBtn_arriba(BtnEliminarClientes);
        BtnAgregarEntrenador.setBtn_arriba_abajo_esquina_ovalado(60);
        BtnAgregarEntrenador.setColor_Hover_text(new java.awt.Color(0, 0, 0));
        BtnAgregarEntrenador.setColor_NoHover_text(new java.awt.Color(153, 153, 153));
        BtnAgregarEntrenador.setEsquina_inferior_izquierdo(40);
        BtnAgregarEntrenador.setEsquina_superior_izquierdo(40);
        BtnAgregarEntrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarEntrenadorActionPerformed(evt);
            }
        });
        AdminMenuView.add(BtnAgregarEntrenador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, 50));

        BtnDesactEntrenador.setForeground(new java.awt.Color(153, 153, 153));
        BtnDesactEntrenador.setText("Desactivar Entrenador");
        BtnDesactEntrenador.setBackground_Hover_1(new java.awt.Color(255, 102, 0));
        BtnDesactEntrenador.setBackground_Hover_2(new java.awt.Color(242, 240, 240));
        BtnDesactEntrenador.setBackground_No_Hover_1(new java.awt.Color(51, 51, 51));
        BtnDesactEntrenador.setBackground_No_Hover_2(new java.awt.Color(51, 51, 51));
        BtnDesactEntrenador.setBtn_arriba(BtnAgregarEntrenador);
        BtnDesactEntrenador.setBtn_arriba_abajo_esquina_ovalado(60);
        BtnDesactEntrenador.setColor_Hover_text(new java.awt.Color(0, 0, 0));
        BtnDesactEntrenador.setColor_NoHover_text(new java.awt.Color(153, 153, 153));
        BtnDesactEntrenador.setEsquina_inferior_izquierdo(40);
        BtnDesactEntrenador.setEsquina_superior_izquierdo(40);
        BtnDesactEntrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDesactEntrenadorActionPerformed(evt);
            }
        });
        AdminMenuView.add(BtnDesactEntrenador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, 50));

        BtnAgregarClientes.setForeground(new java.awt.Color(153, 153, 153));
        BtnAgregarClientes.setText("Agregar Clientes");
        BtnAgregarClientes.setBackground_Hover_1(new java.awt.Color(255, 102, 0));
        BtnAgregarClientes.setBackground_Hover_2(new java.awt.Color(242, 240, 240));
        BtnAgregarClientes.setBackground_No_Hover_1(new java.awt.Color(51, 51, 51));
        BtnAgregarClientes.setBackground_No_Hover_2(new java.awt.Color(51, 51, 51));
        BtnAgregarClientes.setBtn_abajo(BtnEliminarClientes);
        BtnAgregarClientes.setBtn_arriba_abajo_esquina_ovalado(60);
        BtnAgregarClientes.setColor_Hover_text(new java.awt.Color(0, 0, 0));
        BtnAgregarClientes.setColor_NoHover_text(new java.awt.Color(153, 153, 153));
        BtnAgregarClientes.setEsquina_inferior_izquierdo(40);
        BtnAgregarClientes.setEsquina_superior_izquierdo(40);
        BtnAgregarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarClientesActionPerformed(evt);
            }
        });
        AdminMenuView.add(BtnAgregarClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, 50));

        jPanel1.setBackground(new java.awt.Color(242, 240, 240));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        AdminMenuView.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 50, 200));

        imagen_redondo_degradado_JWC1.setBorderSize(2);
        imagen_redondo_degradado_JWC1.setColo1(new java.awt.Color(255, 102, 0));
        imagen_redondo_degradado_JWC1.setColo2(new java.awt.Color(255, 204, 102));
        imagen_redondo_degradado_JWC1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images.png"))); // NOI18N
        AdminMenuView.add(imagen_redondo_degradado_JWC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 110, 100));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username: Admin");
        jLabel1.setToolTipText("");
        AdminMenuView.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 110, -1));

        BtnSalir.setBackground(new java.awt.Color(204, 102, 0));
        BtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/salida.png"))); // NOI18N
        BtnSalir.setText("");
        BtnSalir.setToolTipText("");
        BtnSalir.setArco_esquina(20);
        BtnSalir.setColor_H_text(new java.awt.Color(204, 102, 0));
        BtnSalir.setColor_Hover(new java.awt.Color(255, 255, 255));
        BtnSalir.setColor_Normal(new java.awt.Color(204, 102, 0));
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });
        AdminMenuView.add(BtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 190, 40));

        BtnSalirRedondo.setBackground(new java.awt.Color(204, 102, 0));
        BtnSalirRedondo.setText("");
        BtnSalirRedondo.setArco_esquina(15);
        BtnSalirRedondo.setColor_H_text(new java.awt.Color(204, 102, 0));
        BtnSalirRedondo.setColor_Hover(new java.awt.Color(204, 102, 0));
        BtnSalirRedondo.setColor_Normal(new java.awt.Color(204, 102, 0));
        BtnSalirRedondo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirRedondoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Desactivar Entrenador:");

        Identificacion.setBackground(new java.awt.Color(255, 255, 255));
        Identificacion.setForeground(new java.awt.Color(0, 0, 0));
        Identificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdentificacionActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Ingrese la identificación del entrenador: ");

        BtnEliminar.setBackground(new java.awt.Color(204, 102, 0));
        BtnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/quitar-usuario.png"))); // NOI18N
        BtnEliminar.setText("");
        BtnEliminar.setArco_esquina(20);
        BtnEliminar.setColor_H_text(new java.awt.Color(204, 102, 0));
        BtnEliminar.setColor_Hover(new java.awt.Color(255, 153, 51));
        BtnEliminar.setColor_Normal(new java.awt.Color(204, 102, 0));
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_Round_JWC1Layout = new javax.swing.GroupLayout(panel_Round_JWC1);
        panel_Round_JWC1.setLayout(panel_Round_JWC1Layout);
        panel_Round_JWC1Layout.setHorizontalGroup(
            panel_Round_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Round_JWC1Layout.createSequentialGroup()
                .addComponent(AdminMenuView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panel_Round_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_Round_JWC1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnSalirRedondo, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(panel_Round_JWC1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(panel_Round_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addGroup(panel_Round_JWC1Layout.createSequentialGroup()
                                .addComponent(Identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(251, Short.MAX_VALUE))))
        );
        panel_Round_JWC1Layout.setVerticalGroup(
            panel_Round_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminMenuView, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
            .addGroup(panel_Round_JWC1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panel_Round_JWC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_Round_JWC1Layout.createSequentialGroup()
                        .addComponent(BtnSalirRedondo, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panel_Round_JWC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 620));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAgregarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarClientesActionPerformed
         abrirAgregarClientesView();
    }//GEN-LAST:event_BtnAgregarClientesActionPerformed

    private void BtnSalirRedondoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirRedondoActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BtnSalirRedondoActionPerformed

    private void IdentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdentificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdentificacionActionPerformed

    private void BtnEliminarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarClientesActionPerformed
        abrirEliminarClientesView();
    }//GEN-LAST:event_BtnEliminarClientesActionPerformed

    private void BtnAgregarEntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarEntrenadorActionPerformed
        abrirAgregarEntrenadorView();
    }//GEN-LAST:event_BtnAgregarEntrenadorActionPerformed

    private void BtnDesactEntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDesactEntrenadorActionPerformed
        abrirDesactivarEntrenadorView();
    }//GEN-LAST:event_BtnDesactEntrenadorActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        LoginAdminView loginAdmin = new LoginAdminView();
       loginAdmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        String identificacionObtenida = Identificacion.getText().trim();

        if (identificacionObtenida.length() != 0) {
            try {
                int condicional = JOptionPane.showConfirmDialog(null, "Desea desactivar el entrenador con identificación " + identificacionObtenida + " ?", "Desactivar", JOptionPane.YES_NO_OPTION);

                if (condicional == 0) {
                    entrenadorRepository.deleteEntrenador(identificacionObtenida);
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error al desactivar el entrenador con identificación: " + identificacionObtenida, "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Rellene los campos requeridos: " + identificacionObtenida, "Error", JOptionPane.ERROR);

        }
    }//GEN-LAST:event_BtnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
           // java.util.logging.Logger.getLogger(AdminMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            //java.util.logging.Logger.getLogger(AdminMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            //java.util.logging.Logger.getLogger(AdminMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
           // java.util.logging.Logger.getLogger(AdminMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DesactivarEntrenadorView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Panel_Round_JWC AdminMenuView;
    private btn_efecto01_jwc.btn_efecto_V1_JWC BtnAgregarClientes;
    private btn_efecto01_jwc.btn_efecto_V1_JWC BtnAgregarEntrenador;
    private btn_efecto01_jwc.btn_efecto_V1_JWC BtnDesactEntrenador;
    private swing.Btn_Round_JWC BtnEliminar;
    private btn_efecto01_jwc.btn_efecto_V1_JWC BtnEliminarClientes;
    private swing.Btn_Round_JWC BtnSalir;
    private swing.Btn_Round_JWC BtnSalirRedondo;
    private javax.swing.JFormattedTextField Identificacion;
    private img_redondo_degradado_jwc.imagen_redondo_degradado_JWC imagen_redondo_degradado_JWC1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private swing.Panel_Round_JWC panel_Round_JWC1;
    // End of variables declaration//GEN-END:variables

    private void abrirAgregarClientesView() {
        AgregarClientesView agregarClientes = new AgregarClientesView ();
        agregarClientes.setVisible(true);
        this.dispose();
    }

    private void abrirEliminarClientesView() {
        EliminarClientesView eliminarClientes = new EliminarClientesView ();
        eliminarClientes.setVisible(true);
        this.dispose();
    }

    private void abrirAgregarEntrenadorView() {
        AgregarEntrenadorView agregarEntrenador = new AgregarEntrenadorView ();
        agregarEntrenador.setVisible(true);
        this.dispose();
    }

    private void abrirDesactivarEntrenadorView() {
        DesactivarEntrenadorView desactivarEntrenador = new DesactivarEntrenadorView();
        desactivarEntrenador.setVisible(true);
        this.dispose();
    }
}

