/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AuditFitness.vista.entrenador;

import java.awt.Color;

/**
 *
 * @author deana
 */
public class MostrarProgresoView extends javax.swing.JFrame {
        
    
    /**
     * Creates new form Inicio
     */
    public MostrarProgresoView() {
        initComponents(); setBackground(new Color(0,0,0,0));
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timeSeriesURLGenerator1 = new org.jfree.chart.urls.TimeSeriesURLGenerator();
        EntrenadorMenuView = new swing.Panel_Round_JWC();
        panel_Round_JWC2 = new swing.Panel_Round_JWC();
        BtnAgregarRutina = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        BtnMostrarRutina = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        BtnRegistrarProgreso = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        BtnMostrarProgreso = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        BtnMostrarAsistencia = new btn_efecto01_jwc.btn_efecto_V1_JWC();
        jPanel1 = new javax.swing.JPanel();
        imagen_redondo_degradado_JWC1 = new img_redondo_degradado_jwc.imagen_redondo_degradado_JWC();
        lbUsername = new javax.swing.JLabel();
        BtnSalir = new swing.Btn_Round_JWC();
        BtnSalirRedondo = new swing.Btn_Round_JWC();
        jLabel1 = new javax.swing.JLabel();
        Identificacion = new javax.swing.JFormattedTextField();
        BtnEnviar = new swing.Btn_Round_JWC();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Identificacion1 = new javax.swing.JFormattedTextField();
        BtnEnviar1 = new swing.Btn_Round_JWC();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EntrenadorMenuView.setBackground(new java.awt.Color(242, 240, 240));
        EntrenadorMenuView.setEsqInferiorDerecha(50);
        EntrenadorMenuView.setEsqInferiorIzquierda(50);
        EntrenadorMenuView.setEsqSuperiorDerecha(50);
        EntrenadorMenuView.setEsqSuperiorIzquierda(50);

        panel_Round_JWC2.setBackground(new java.awt.Color(51, 51, 51));
        panel_Round_JWC2.setEsqInferiorIzquierda(50);
        panel_Round_JWC2.setEsqSuperiorIzquierda(50);
        panel_Round_JWC2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnAgregarRutina.setForeground(new java.awt.Color(153, 153, 153));
        BtnAgregarRutina.setText("Agregar Rutina");
        BtnAgregarRutina.setBackground_Hover_1(new java.awt.Color(255, 102, 0));
        BtnAgregarRutina.setBackground_Hover_2(new java.awt.Color(242, 240, 240));
        BtnAgregarRutina.setBackground_No_Hover_1(new java.awt.Color(51, 51, 51));
        BtnAgregarRutina.setBackground_No_Hover_2(new java.awt.Color(51, 51, 51));
        BtnAgregarRutina.setBtn_abajo(BtnMostrarRutina);
        BtnAgregarRutina.setBtn_arriba_abajo_esquina_ovalado(60);
        BtnAgregarRutina.setColor_Hover_text(new java.awt.Color(0, 0, 0));
        BtnAgregarRutina.setColor_NoHover_text(new java.awt.Color(153, 153, 153));
        BtnAgregarRutina.setEsquina_inferior_izquierdo(40);
        BtnAgregarRutina.setEsquina_superior_izquierdo(40);
        BtnAgregarRutina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarRutinaActionPerformed(evt);
            }
        });
        panel_Round_JWC2.add(BtnAgregarRutina, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, 50));

        BtnMostrarRutina.setForeground(new java.awt.Color(153, 153, 153));
        BtnMostrarRutina.setText("Mostrar Rutina");
        BtnMostrarRutina.setBackground_Hover_1(new java.awt.Color(255, 102, 0));
        BtnMostrarRutina.setBackground_Hover_2(new java.awt.Color(242, 240, 240));
        BtnMostrarRutina.setBackground_No_Hover_1(new java.awt.Color(51, 51, 51));
        BtnMostrarRutina.setBackground_No_Hover_2(new java.awt.Color(51, 51, 51));
        BtnMostrarRutina.setBtn_abajo(BtnRegistrarProgreso);
        BtnMostrarRutina.setBtn_arriba(BtnAgregarRutina);
        BtnMostrarRutina.setBtn_arriba_abajo_esquina_ovalado(60);
        BtnMostrarRutina.setColor_Hover_text(new java.awt.Color(0, 0, 0));
        BtnMostrarRutina.setColor_NoHover_text(new java.awt.Color(153, 153, 153));
        BtnMostrarRutina.setEsquina_inferior_izquierdo(40);
        BtnMostrarRutina.setEsquina_superior_izquierdo(40);
        panel_Round_JWC2.add(BtnMostrarRutina, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, 50));

        BtnRegistrarProgreso.setForeground(new java.awt.Color(153, 153, 153));
        BtnRegistrarProgreso.setText("Registrar Progreso");
        BtnRegistrarProgreso.setBackground_Hover_1(new java.awt.Color(255, 102, 0));
        BtnRegistrarProgreso.setBackground_Hover_2(new java.awt.Color(242, 240, 240));
        BtnRegistrarProgreso.setBackground_No_Hover_1(new java.awt.Color(51, 51, 51));
        BtnRegistrarProgreso.setBackground_No_Hover_2(new java.awt.Color(51, 51, 51));
        BtnRegistrarProgreso.setBtn_abajo(BtnMostrarProgreso);
        BtnRegistrarProgreso.setBtn_arriba(BtnMostrarRutina);
        BtnRegistrarProgreso.setBtn_arriba_abajo_esquina_ovalado(60);
        BtnRegistrarProgreso.setColor_Hover_text(new java.awt.Color(0, 0, 0));
        BtnRegistrarProgreso.setColor_NoHover_text(new java.awt.Color(153, 153, 153));
        BtnRegistrarProgreso.setEsquina_inferior_izquierdo(40);
        BtnRegistrarProgreso.setEsquina_superior_izquierdo(40);
        panel_Round_JWC2.add(BtnRegistrarProgreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, 50));

        BtnMostrarProgreso.setForeground(new java.awt.Color(153, 153, 153));
        BtnMostrarProgreso.setText("Mostrar Progreso");
        BtnMostrarProgreso.setBackground_Hover_1(new java.awt.Color(255, 102, 0));
        BtnMostrarProgreso.setBackground_Hover_2(new java.awt.Color(242, 240, 240));
        BtnMostrarProgreso.setBackground_No_Hover_1(new java.awt.Color(51, 51, 51));
        BtnMostrarProgreso.setBackground_No_Hover_2(new java.awt.Color(51, 51, 51));
        BtnMostrarProgreso.setBtn_abajo(BtnMostrarAsistencia);
        BtnMostrarProgreso.setBtn_arriba(BtnRegistrarProgreso);
        BtnMostrarProgreso.setBtn_arriba_abajo_esquina_ovalado(60);
        BtnMostrarProgreso.setColor_Hover_text(new java.awt.Color(0, 0, 0));
        BtnMostrarProgreso.setColor_NoHover_text(new java.awt.Color(153, 153, 153));
        BtnMostrarProgreso.setEsquina_inferior_izquierdo(40);
        BtnMostrarProgreso.setEsquina_superior_izquierdo(40);
        panel_Round_JWC2.add(BtnMostrarProgreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, 50));

        BtnMostrarAsistencia.setForeground(new java.awt.Color(153, 153, 153));
        BtnMostrarAsistencia.setText("Mostrar Asistencia");
        BtnMostrarAsistencia.setBackground_Hover_1(new java.awt.Color(255, 102, 0));
        BtnMostrarAsistencia.setBackground_Hover_2(new java.awt.Color(242, 240, 240));
        BtnMostrarAsistencia.setBackground_No_Hover_1(new java.awt.Color(51, 51, 51));
        BtnMostrarAsistencia.setBackground_No_Hover_2(new java.awt.Color(51, 51, 51));
        BtnMostrarAsistencia.setBtn_abajo(BtnMostrarAsistencia);
        BtnMostrarAsistencia.setBtn_arriba(BtnMostrarProgreso);
        BtnMostrarAsistencia.setBtn_arriba_abajo_esquina_ovalado(60);
        BtnMostrarAsistencia.setColor_Hover_text(new java.awt.Color(0, 0, 0));
        BtnMostrarAsistencia.setColor_NoHover_text(new java.awt.Color(153, 153, 153));
        BtnMostrarAsistencia.setEsquina_inferior_izquierdo(40);
        BtnMostrarAsistencia.setEsquina_superior_izquierdo(40);
        panel_Round_JWC2.add(BtnMostrarAsistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, 50));

        jPanel1.setBackground(new java.awt.Color(242, 240, 240));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panel_Round_JWC2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 50, 250));

        imagen_redondo_degradado_JWC1.setBorderSize(2);
        imagen_redondo_degradado_JWC1.setColo1(new java.awt.Color(255, 102, 0));
        imagen_redondo_degradado_JWC1.setColo2(new java.awt.Color(255, 204, 102));
        imagen_redondo_degradado_JWC1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images.png"))); // NOI18N
        panel_Round_JWC2.add(imagen_redondo_degradado_JWC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 110, 100));

        lbUsername.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        lbUsername.setForeground(new java.awt.Color(255, 255, 255));
        lbUsername.setText("Username: Entrenador");
        lbUsername.setToolTipText("");
        panel_Round_JWC2.add(lbUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, 20));

        BtnSalir.setBackground(new java.awt.Color(204, 102, 0));
        BtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/salida.png"))); // NOI18N
        BtnSalir.setText("");
        BtnSalir.setArco_esquina(20);
        BtnSalir.setColor_H_text(new java.awt.Color(204, 102, 0));
        BtnSalir.setColor_Hover(new java.awt.Color(255, 255, 255));
        BtnSalir.setColor_Normal(new java.awt.Color(204, 102, 0));
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });
        panel_Round_JWC2.add(BtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 190, 40));

        BtnSalirRedondo.setBackground(new java.awt.Color(204, 102, 0));
        BtnSalirRedondo.setText("");
        BtnSalirRedondo.setArco_esquina(15);
        BtnSalirRedondo.setColor_H_text(new java.awt.Color(204, 102, 0));
        BtnSalirRedondo.setColor_Hover(new java.awt.Color(204, 102, 0));
        BtnSalirRedondo.setColor_Normal(new java.awt.Color(204, 102, 0));
        BtnSalirRedondo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirRedondoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Ingrese la identificación del cliente: ");

        Identificacion.setBackground(new java.awt.Color(255, 255, 255));
        Identificacion.setForeground(new java.awt.Color(0, 0, 0));
        Identificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdentificacionActionPerformed(evt);
            }
        });

        BtnEnviar.setBackground(new java.awt.Color(204, 102, 0));
        BtnEnviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/parte-superior-del-avion-de-papel.png"))); // NOI18N
        BtnEnviar.setText("");
        BtnEnviar.setArco_esquina(20);
        BtnEnviar.setColor_H_text(new java.awt.Color(204, 102, 0));
        BtnEnviar.setColor_Hover(new java.awt.Color(255, 153, 51));
        BtnEnviar.setColor_Normal(new java.awt.Color(204, 102, 0));
        BtnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEnviarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Progreso del cliente: ");

        jPanel2.setBackground(new java.awt.Color(242, 240, 240));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        Identificacion1.setBackground(new java.awt.Color(255, 255, 255));
        Identificacion1.setForeground(new java.awt.Color(0, 0, 0));
        Identificacion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Identificacion1ActionPerformed(evt);
            }
        });

        BtnEnviar1.setBackground(new java.awt.Color(204, 102, 0));
        BtnEnviar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/parte-superior-del-avion-de-papel.png"))); // NOI18N
        BtnEnviar1.setText("");
        BtnEnviar1.setArco_esquina(20);
        BtnEnviar1.setColor_H_text(new java.awt.Color(204, 102, 0));
        BtnEnviar1.setColor_Hover(new java.awt.Color(255, 153, 51));
        BtnEnviar1.setColor_Normal(new java.awt.Color(204, 102, 0));
        BtnEnviar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEnviar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EntrenadorMenuViewLayout = new javax.swing.GroupLayout(EntrenadorMenuView);
        EntrenadorMenuView.setLayout(EntrenadorMenuViewLayout);
        EntrenadorMenuViewLayout.setHorizontalGroup(
            EntrenadorMenuViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EntrenadorMenuViewLayout.createSequentialGroup()
                .addComponent(panel_Round_JWC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(EntrenadorMenuViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EntrenadorMenuViewLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnSalirRedondo, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(EntrenadorMenuViewLayout.createSequentialGroup()
                        .addGroup(EntrenadorMenuViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EntrenadorMenuViewLayout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addGroup(EntrenadorMenuViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(EntrenadorMenuViewLayout.createSequentialGroup()
                                        .addComponent(Identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(BtnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(EntrenadorMenuViewLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(EntrenadorMenuViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(EntrenadorMenuViewLayout.createSequentialGroup()
                                        .addComponent(Identificacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(BtnEnviar1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2)))
                            .addGroup(EntrenadorMenuViewLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(51, Short.MAX_VALUE))))
        );
        EntrenadorMenuViewLayout.setVerticalGroup(
            EntrenadorMenuViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Round_JWC2, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
            .addGroup(EntrenadorMenuViewLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(BtnSalirRedondo, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EntrenadorMenuViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Identificacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(EntrenadorMenuViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnEnviar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Identificacion1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(EntrenadorMenuView, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 620));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAgregarRutinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarRutinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAgregarRutinaActionPerformed

    private void BtnSalirRedondoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirRedondoActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BtnSalirRedondoActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void IdentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdentificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdentificacionActionPerformed

    private void BtnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEnviarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnEnviarActionPerformed

    private void Identificacion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Identificacion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Identificacion1ActionPerformed

    private void BtnEnviar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEnviar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnEnviar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarProgresoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarProgresoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarProgresoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarProgresoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarProgresoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private btn_efecto01_jwc.btn_efecto_V1_JWC BtnAgregarRutina;
    private swing.Btn_Round_JWC BtnEnviar;
    private swing.Btn_Round_JWC BtnEnviar1;
    private btn_efecto01_jwc.btn_efecto_V1_JWC BtnMostrarAsistencia;
    private btn_efecto01_jwc.btn_efecto_V1_JWC BtnMostrarProgreso;
    private btn_efecto01_jwc.btn_efecto_V1_JWC BtnMostrarRutina;
    private btn_efecto01_jwc.btn_efecto_V1_JWC BtnRegistrarProgreso;
    private swing.Btn_Round_JWC BtnSalir;
    private swing.Btn_Round_JWC BtnSalirRedondo;
    private swing.Panel_Round_JWC EntrenadorMenuView;
    private javax.swing.JFormattedTextField Identificacion;
    private javax.swing.JFormattedTextField Identificacion1;
    private img_redondo_degradado_jwc.imagen_redondo_degradado_JWC imagen_redondo_degradado_JWC1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbUsername;
    private swing.Panel_Round_JWC panel_Round_JWC2;
    private org.jfree.chart.urls.TimeSeriesURLGenerator timeSeriesURLGenerator1;
    // End of variables declaration//GEN-END:variables
}
